### ISSUE TITLE
Hi sir, Iam just a beginner in ROS and Robotics. So that with my littile knowledge in that, i encountered witha an rror like this in last 3 days! can you give me any suggestions?

### ISSUE THREAD

**Issue by avinashsen707** [yehengchen/YOLOv3-ROS#1]
trinity@NCRAI:~/catkin_ws$ catkin_make -DCMAKE_BUILD_TYPE=Release
Base path: /home/trinity/catkin_ws
Source space: /home/trinity/catkin_ws/src
Build space: /home/trinity/catkin_ws/build
Devel space: /home/trinity/catkin_ws/devel
Install space: /home/trinity/catkin_ws/install
####
####
####
####
[  0%] Built target sensor_msgs_generate_messages_py
[  0%] Built target actionlib_msgs_generate_messages_py
[  0%] Built target _darknet_ros_msgs_generate_messages_check_deps_BoundingBox
[  0%] Built target _darknet_ros_msgs_generate_messages_check_deps_BoundingBoxes
[  0%] Built target _darknet_ros_msgs_generate_messages_check_deps_CheckForObjectsResult
[  0%] Built target _darknet_ros_msgs_generate_messages_check_deps_CheckForObjectsFeedback
[  0%] Built target geometry_msgs_generate_messages_py
[  0%] Built target std_msgs_generate_messages_py
[  0%] Built target _darknet_ros_msgs_generate_messages_check_deps_CheckForObjectsActionResult
[  0%] Built target _darknet_ros_msgs_generate_messages_check_deps_CheckForObjectsAction
[  0%] Built target _darknet_ros_msgs_generate_messages_check_deps_CheckForObjectsGoal
[  0%] Built target _darknet_ros_msgs_generate_messages_check_deps_CheckForObjectsActionFeedback
[  0%] Built target geometry_msgs_generate_messages_cpp
[  0%] Built target sensor_msgs_generate_messages_cpp
[  0%] Built target _darknet_ros_msgs_generate_messages_check_deps_CheckForObjectsActionGoal
[  0%] Built target std_msgs_generate_messages_cpp
[  0%] Built target actionlib_msgs_generate_messages_cpp
[  0%] Built target sensor_msgs_generate_messages_nodejs
[  0%] Built target actionlib_msgs_generate_messages_nodejs
[  0%] Built target geometry_msgs_generate_messages_nodejs
[  0%] Built target std_msgs_generate_messages_nodejs
[  0%] Built target geometry_msgs_generate_messages_lisp
[  0%] Built target std_msgs_generate_messages_lisp
[  0%] Built target sensor_msgs_generate_messages_lisp
[  0%] Built target geometry_msgs_generate_messages_eus
[  0%] Built target actionlib_msgs_generate_messages_lisp
[  0%] Built target std_msgs_generate_messages_eus
[  0%] Built target actionlib_msgs_generate_messages_eus
[  0%] Built target sensor_msgs_generate_messages_eus
[ 33%] Built target darknet_ros_msgs_generate_messages_cpp
[ 35%] Built target darknet_ros_msgs_generate_messages_py
[ 51%] Built target darknet_ros_msgs_generate_messages_nodejs
[ 87%] Built target darknet_ros_msgs_generate_messages_lisp
[ 87%] Built target darknet_ros_msgs_generate_messages_eus
[ 87%] Built target darknet_ros_msgs_generate_messages
[ 88%] Linking CXX shared library /home/trinity/catkin_ws/devel/lib/libdarknet_ros_lib.so
[ 92%] Built target usb_cam
[ 96%] Built target usb_cam_node
/usr/bin/ld: cannot find -lcuda
collect2: error: ld returned 1 exit status
YOLOv3_ROS/darknet_ros/CMakeFiles/darknet_ros_lib.dir/build.make:189: recipe for target '/home/trinity/catkin_ws/devel/lib/libdarknet_ros_lib.so' failed
make[2]: *** [/home/trinity/catkin_ws/devel/lib/libdarknet_ros_lib.so] Error 1
CMakeFiles/Makefile2:2390: recipe for target 'YOLOv3_ROS/darknet_ros/CMakeFiles/darknet_ros_lib.dir/all' failed
make[1]: *** [YOLOv3_ROS/darknet_ros/CMakeFiles/darknet_ros_lib.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j4 -l4" failed

**Comment by yehengchen** [comment]
@avinashsen707  Are you use the ROS-melodic ?

**Comment by avinashsen707** [comment]
No Sir I am Using Ros-Knetic with ubuntu 16.04 lts

**Comment by yehengchen** [comment]
@avinashsen707 
I'm also using ROS-Kinetic with ubuntu 16.04 LTS.
Please check the `$ gcc -lhdf5 --verbose`

**Comment by avinashsen707** [comment]
while i run the code: its showed as...



trinity@NCRAI:~/catkin_ws$ gcc -lhdf5 --verbose
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.5.0-12ubuntu1~16.04' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 5.5.0 20171010 (Ubuntu 5.5.0-12ubuntu1~16.04) 
COMPILER_PATH=/usr/lib/gcc/x86_64-linux-gnu/5/:/usr/lib/gcc/x86_64-linux-gnu/5/:/usr/lib/gcc/x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/5/:/usr/lib/gcc/x86_64-linux-gnu/
LIBRARY_PATH=/usr/lib/gcc/x86_64-linux-gnu/5/:/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/:/lib/x86_64-linux-gnu/:/lib/../lib/:/usr/lib/x86_64-linux-gnu/:/usr/lib/../lib/:/usr/lib/gcc/x86_64-linux-gnu/5/../../../:/lib/:/usr/lib/
COLLECT_GCC_OPTIONS='-v' '-mtune=generic' '-march=x86-64'
 /usr/lib/gcc/x86_64-linux-gnu/5/collect2 -plugin /usr/lib/gcc/x86_64-linux-gnu/5/liblto_plugin.so -plugin-opt=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper -plugin-opt=-fresolution=/tmp/ccmAGDek.res -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lc -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s --sysroot=/ --build-id --eh-frame-hdr -m elf_x86_64 --hash-style=gnu --as-needed -dynamic-linker /lib64/ld-linux-x86-64.so.2 -z relro /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/crt1.o /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/crti.o /usr/lib/gcc/x86_64-linux-gnu/5/crtbegin.o -L/usr/lib/gcc/x86_64-linux-gnu/5 -L/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib -L/lib/x86_64-linux-gnu -L/lib/../lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/5/../../.. -lhdf5 -lgcc --push-state --as-needed -lgcc_s --pop-state -lc -lgcc --push-state --as-needed -lgcc_s --pop-state /usr/lib/gcc/x86_64-linux-gnu/5/crtend.o /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/crtn.o
/usr/bin/ld: cannot find -lhdf5
collect2: error: ld returned 1 exit status

**Comment by yehengchen** [comment]
@avinashsen707 try  `catkin_make -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=/usr/bin/gcc-6`

**Comment by avinashsen707** [comment]
> @avinashsen707 try `catkin_make -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=/usr/bin/gcc-6`

let me try and convey you soon
