### ISSUE TITLE
DARKNET_PATH-NOTFOUND/src/activation_layer.c

### ISSUE THREAD

**Issue by Yanxing-Shi** [yehengchen/YOLOv3-ROS#2]
你好，我在编译过程中出现了以下错误：
```
CMake Error at /usr/share/cmake-3.5/Modules/FindCUDA.cmake:1649 (add_library):
  Cannot find source file:

    DARKNET_PATH-NOTFOUND/src/activation_layer.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx
Call Stack (most recent call first):
  YOLOv3_ROS/darknet_ros/CMakeLists.txt:97 (cuda_add_library)
```

-- Generating done
-- Build files have been written to: /home/user/experiment/ros/catkin_workspace/build
Invoking "cmake" failed

**Comment by yehengchen** [comment]
@syx0629 你试一下把 darknet_ros 删了，用下面的方法下载
` git clone --recursive git@github.com:leggedrobotics/darknet_ros.git`

**Comment by mgagnier93** [comment]
Hi!

I'm having the same issue. I tried cloning that repo but it looks like I don't have the rights, any tips?

Command and error message below:

git clone --recursive gagnier@uw.edu@github.com:leggedrobotics/darknet_ros.git
Cloning into 'darknet_ros'...
gagnier@uw.edu@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by mgagnier93** [comment]
@yehengchen I followed your instructions on to clone the repo, but now I am getting this error when trying "catkin_make yolov3_pytorch_ros":

#### Running command: "make cmake_check_build_system" in "/home/mike/catkin_ws/build"
####
####
#### Running command: "make yolov3_pytorch_ros -j8 -l8" in "/home/mike/catkin_ws/build"
####
make: *** No rule to make target 'yolov3_pytorch_ros'.  Stop.
Invoking "make yolov3_pytorch_ros -j8 -l8" failed

Any ideas on how to fix this issue? Thank you. 

Edit: This worked for me "git clone --recursive https://github.com/leggedrobotics/darknet_ros.git"
