### ISSUE TITLE
When I use catkin_make yolov3_pytorch_ros ，It's show below

### ISSUE THREAD

**Issue by Robotmaid** [yehengchen/YOLOv3-ROS#7]
```
-- +++ processing catkin package: 'yolov3_pytorch_ros'
-- ==> add_subdirectory(YOLOv3-ROS/yolov3_pytorch_ros)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- yolov3_pytorch_ros: 2 messages, 0 services
-- Configuring done
-- Generating done
-- Build files have been written to: /headless/Desktop/catkin_ws/build
####
#### Running command: "make yolov3_pytorch_ros -j8 -l8" in "/headless/Desktop/catkin_ws/build"
####
make: *** No rule to make target 'yolov3_pytorch_ros'.  Stop.
Invoking "make yolov3_pytorch_ros -j8 -l8" failed
```

How can I do for this?

Thank you for your help.

**Comment by Zhangeaky** [comment]
you might use  catkin_make -DCATKIN_WHITELIST_PACKAGES="yolov3_pytorch_ros"

**Comment by Robotmaid** [comment]
> you might use catkin_make -DCATKIN_WHITELIST_PACKAGES="yolov3_pytorch_ros"

Thank you for your help.I catkin_make it successfully.

**Comment by liuqiang1227** [comment]
@Zhangeaky  用了这个方法catkin_make成功了 ，但是 roslaunch yolov3_pytorch_ros detector.launch出错了，错误如下：

ERROR: cannot launch node of type [yolov3_pytorch_ros/detector.py]: Cannot locate node of type [detector.py] in package [yolov3_pytorch_ros]. Make sure file exists in package path and permission is set to executable (chmod +x)
